from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

from phd_consulting_agent.models import GeneratedOutput, OutputKind, ProvenanceKind, SourceFact
from phd_consulting_agent.skill_contracts import SkillRequest
from phd_consulting_agent.skill_prompts import build_prompt

BACKEND_DIR = Path(__file__).resolve().parents[1]
load_dotenv(BACKEND_DIR / ".env")

SKILL_OUTPUTS = {
    "student_profile_analysis": (OutputKind.BACKGROUND_ANALYSIS, "背景分析"),
    "research_direction_design": (OutputKind.RESEARCH_DIRECTIONS, "研究方向建议"),
    "school_supervisor_matching": (OutputKind.SCHOOL_SUPERVISOR_MATCHING, "学校/项目/导师匹配"),
    "comparable_case_generator": (OutputKind.COMPARABLE_CASES, "可比参考案例"),
    "consultant_delivery_rewriter": (OutputKind.DELIVERY_REWRITE, "顾问话术改写"),
    "consultation_call_prep": (OutputKind.CALL_PREP, "咨询电话准备包"),
}


class MockSkillRunner:
    def run(self, skill_name: str, request: SkillRequest) -> GeneratedOutput:
        if skill_name not in SKILL_OUTPUTS:
            raise ValueError(f"Unknown skill: {skill_name}")
        kind, title = SKILL_OUTPUTS[skill_name]
        prompt = build_prompt(skill_name, request)
        return GeneratedOutput(
            case_id=request.case.id,
            kind=kind,
            title=title,
            content=f"Mock output for {skill_name}.\n\nPrompt preview:\n{prompt[:600]}",
            sources=[
                SourceFact(
                    kind=ProvenanceKind.MODEL_STRATEGY,
                    label="mock_runner",
                    value="This output was generated by the local mock runner.",
                )
            ],
        )


class RealSkillRunner:
    def __init__(self):
        api_key = os.getenv("OPENAI_API_KEY")
        base_url = os.getenv("OPENAI_BASE_URL")

        if not api_key:
            raise ValueError("OPENAI_API_KEY is missing. Please set it in app/backend/.env")
        if not base_url:
            raise ValueError("OPENAI_BASE_URL is missing. Please set it in app/backend/.env")
        if not base_url.startswith(("http://", "https://")):
            raise ValueError("OPENAI_BASE_URL must start with http:// or https://")

        self.client = OpenAI(
            api_key=api_key,
            base_url=base_url.rstrip("/"),
        )
        self.model = os.getenv("MODEL_NAME", "gpt-4o-mini")

    def run(self, skill_name: str, request: SkillRequest) -> GeneratedOutput:
        if skill_name not in SKILL_OUTPUTS:
            raise ValueError(f"Unknown skill: {skill_name}")

        kind, title = SKILL_OUTPUTS[skill_name]
        prompt = build_prompt(skill_name, request)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are a professional PhD consulting expert."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
        )

        content = response.choices[0].message.content or ""

        return GeneratedOutput(
            case_id=request.case.id,
            kind=kind,
            title=title,
            content=content,
            sources=[
                SourceFact(
                    kind=ProvenanceKind.MODEL_STRATEGY,
                    label="llm_runner",
                    value=f"Generated via LLM model: {self.model}",
                )
            ],
        )


def get_runner():
    mode = os.getenv("RUNNER_MODE", "mock").strip().lower()
    if mode == "real":
        return RealSkillRunner()
    return MockSkillRunner()
